### ISSUE TITLE
您好，请问能用一下这个工具吗

### ISSUE THREAD

**Issue by Zzhanp** [isee15/ctf-tools#1]
您好，请问能用一下这个工具吗~

**Comment by isee15** [comment]
重新生成了一下执行文件，下载zip
https://github.com/isee15/ctf-tools/blob/master/JiayuTools.zip，
然后执行 java -jar JiayuTools.jar

**Comment by Zzhanp** [comment]
> 重新生成了一下执行文件，下载zip
> [https://github.com/isee15/ctf-tools/blob/master/JiayuTools.zip，](https://github.com/isee15/ctf-tools/blob/master/JiayuTools.zip%EF%BC%8C)
> 然后执行 java -jar JiayuTools.jar
嗯嗯 谢谢您~

**Comment by Zzhanp** [comment]
您好，很抱歉又打扰您了。按照您说的，下载zip，刚才运行了一下，报错
错误: 找不到或无法加载主类 ctf.Main
原因: java.lang.NoClassDefFoundError: javafx/application/Application

**Comment by isee15** [comment]
> 您好，很抱歉又打扰您了。按照您说的，下载zip，刚才运行了一下，报错
> 错误: 找不到或无法加载主类 ctf.Main
> 原因: java.lang.NoClassDefFoundError: javafx/application/Application

需要安装javafx运行环境
