### ISSUE TITLE
没看到破解 zip 的地方呀

### ISSUE THREAD

**Issue by KysonGeek** [isee15/ctf-tools#2]

**Comment by isee15** [comment]
菜单上有zip和zipcrc。zip里面主要处理伪加密。zipcrc是进行crc的猜解。

**Comment by KysonGeek** [comment]
我可能没有描述清楚。
我从网上下载了一个压缩文件（.zip），解压的时候发现有密码，我想破解出这个文件的解压密码

**Comment by isee15** [comment]
ctftools不包含破解zip密码的功能。可以搜ARCHPR这个工具可以
